FROM registry.digitalocean.com/visionary/app/base

RUN apt-get update
RUN apt-get install -y \
    git \
    zip \
    curl \
    sudo \
    unzip \
    libicu-dev \
    libbz2-dev \
    libpng-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libreadline-dev \
    libfreetype6-dev \
    g++

ENV APACHE_DOCUMENT_ROOT=/var/www/html
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite headers

RUN docker-php-ext-install \
    bz2 \
    intl \
    iconv \
    bcmath \
    opcache \
    calendar \
    mbstring \
    pdo_mysql \
    zip  \
    mysqli 


COPY --from=composer:1.10 /usr/bin/composer /usr/bin/composer
RUN sed -i 's/128M/512M/g' /usr/local/etc/php/php.ini-production
RUN sed -i 's/128M/512M/g' /usr/local/etc/php/php.ini-development

RUN cp -r /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
WORKDIR /var/www/html/
COPY . /var/www/html/
RUN chown -R "www-data:www-data" .
RUN chmod -R 0755 .
RUN chmod -R 0777 storage

EXPOSE 80



